// Global CSSS
import "../styles/globals.css";
// Layout CSS
import "../styles/scss/app.scss";
import "../styles/scss/navbar.scss";
import "../styles/scss/resume-card.scss";
import "../styles/scss/skill-card.scss";
import "../styles/scss/sidebar.scss";
import "../styles/scss/social-list.scss";
// Pages CSS
import "../styles/scss/pages/about.scss";
import "../styles/scss/pages/blog.scss";
import "../styles/scss/pages/contact.scss";
import "../styles/scss/pages/portfolio.scss";
import "../styles/scss/pages/resume.scss";
import "../styles/home.scss";
import "../styles/scss/admin/all.scss";
import Head from "next/head";
import NavBar from "../components/Layout/NavBar";
import { Container, Row, Col } from "react-bootstrap";
import { motion } from "framer-motion";
import Sidebar from "../components/Sidebar";
import "bootstrap/dist/css/bootstrap.min.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Abdulrahman Fani - Senior Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Container>
        <Row className="main-row">
          <Col xs={12} sm={12} md={4} lg={4}>
            <motion.div
              initial={{
                x: "-50%",
                opacity: 0,
                scale: 0.5,
              }}
              animate={{
                x: 0,
                opacity: 1,
                scale: 1,
                transition: { duration: 0.5 },
              }}
            >
              <Sidebar />
            </motion.div>
          </Col>
          <Col xs={12} sm={12} md={8} lg={8}>
            <div className="content-card-container">
              <Component {...pageProps} />
            </div>
          </Col>
        </Row>
      </Container>
    </>
  );
}

export default MyApp;
